// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCw1K8rby6Tdr0qRD23PJcAIpAOoeCBoQ',
    appId: '1:741158003751:web:d51eaba55c668e3d251a02',
    messagingSenderId: '741158003751',
    projectId: 'machine-test-ca80f',
    authDomain: 'machine-test-ca80f.firebaseapp.com',
    storageBucket: 'machine-test-ca80f.appspot.com',
    measurementId: 'G-7BBX2GHGW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wtFB7Brv0b0sBE_i-liDy6utmHbIIcE',
    appId: '1:741158003751:android:8a431818f5fe8e35251a02',
    messagingSenderId: '741158003751',
    projectId: 'machine-test-ca80f',
    storageBucket: 'machine-test-ca80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6e5CAb-tWT3geRhlap1hocVjuXg52w9c',
    appId: '1:741158003751:ios:2d99b486e03b8b88251a02',
    messagingSenderId: '741158003751',
    projectId: 'machine-test-ca80f',
    storageBucket: 'machine-test-ca80f.appspot.com',
    iosBundleId: 'com.example.machineTestTotalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6e5CAb-tWT3geRhlap1hocVjuXg52w9c',
    appId: '1:741158003751:ios:2d99b486e03b8b88251a02',
    messagingSenderId: '741158003751',
    projectId: 'machine-test-ca80f',
    storageBucket: 'machine-test-ca80f.appspot.com',
    iosBundleId: 'com.example.machineTestTotalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCw1K8rby6Tdr0qRD23PJcAIpAOoeCBoQ',
    appId: '1:741158003751:web:722e73c423ffc516251a02',
    messagingSenderId: '741158003751',
    projectId: 'machine-test-ca80f',
    authDomain: 'machine-test-ca80f.firebaseapp.com',
    storageBucket: 'machine-test-ca80f.appspot.com',
    measurementId: 'G-PBSPYZ4HZ4',
  );
}
